name: PHP Linting

on:
  - push
  - pull_request

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v1
        with:
          # Specify the PHP version
          php-version: '7.3'
      - name: Install
        # Install project
        run: make install
      - name: Run linter
        # Run Linter
        run: make lint